name: Test React App

on: 
  push: 
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2      # -name: Setup Node v14
      - run: ls - la
      - name: Setup Node v14
        uses: actions/setup-node@v1
        with: 
          node-version: 14.x
      - run: yarn

